
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class symu {
  /* terminals */
  public static final int entero = 3;
  public static final int pc = 6;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final int dp = 5;
  public static final int c = 4;
  public static final int id = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "entero",
  "c",
  "dp",
  "pc"
  };
}

